language: java
jdk:
  - openjdk8

before_deploy:
  - gem install faraday -v 2.8.1
  - gem install faraday-net_http -v 3.0.2

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-shop-demo"
  on:
    branch: main